### ISSUE TITLE
HTTP Code 451 missing as Status

### ISSUE THREAD

**Issue by shexbeer** [zalando/problem#102]
The http error code 451 (Unavailable for legal reasons) is not supported by Status at the moment.

## Description
https://tools.ietf.org/html/rfc7725

## Expected Behavior
Support HttpStatus 451

## Actual Behavior
Does not support HttpStatus 451

## Possible Fix
Implement in Status.java

**Comment by whiskeysierra** [comment]
Thanks for raising the issue. Would you be willing to prepare a pull request?

**Comment by shexbeer** [comment]
I will make a PR, stay tuned

**Comment by shexbeer** [comment]
You can find the PR related to this issue here: https://github.com/zalando/problem/pull/104
