### ISSUE TITLE
Problem message should not include title

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/problem#13]
Currently problem message is composed with title and message.
As there is separate title field already present, message field should not contain title.

**Comment by whiskeysierra** [comment]
Do you mean `Throwable.getMessage`? It's a composition of `title` and `detail`. A problem doesn't have a  `message` property.

**Comment by AlexanderYastrebov** [comment]
ProblemModule was not registered properly and that is why I observed unintended fields in output. Cosing this as unrelevant.
