### ISSUE TITLE
getCause() in java.lang.Throwable clashes with getCause() in org.zalando.problem.Exceptional

### ISSUE THREAD

**Issue by kalexmills** [zalando/problem#132]
When implementing `Exceptional` on my business exceptions that extend RuntimeException, I am seeing compiler errors due to a clash with the `Exceptional` interface.

## Description

It turns out that `getCause` is already implemented in `java.lang.Throwable`, and it is required to throw a Throwable there.

## Expected Behavior

The intended use-case in which `Exceptional` can be used as a marker interface for existing business exceptions should not conflict with existing Java classes.

## Actual Behavior

Using `Exceptional` as a marker interface on exceptions that extend Throwable causes compile-time errors.

## Possible Fix

1) Remove `Exceptional getCause();` from the `Exceptional` definition.
2) (bad idea) Generify Exceptional to take as a type-parameter the result of getCause().

Remove

## Steps to Reproduce
compile this minimal (and stupid) implementation with Java 11

```
public class AttemptExceptional extends Exception implements Exceptional {

  @Override
  public Exception propagate() throws Exception {
    return null;
  }

  @Override
  public <X extends Throwable> X propagateAs(Class<X> type) throws X {
    return null;
  }

  @Override
  public URI getType() {
    return null;
  }

  @Nullable
  @Override
  public String getTitle() {
    return null;
  }

  @Nullable
  @Override
  public StatusType getStatus() {
    return null;
  }

  @Nullable
  @Override
  public String getDetail() {
    return null;
  }

  @Nullable
  @Override
  public URI getInstance() {
    return null;
  }

  @Override
  public Map<String, Object> getParameters() {
    return null;
  }
}

```

## Your Environment

Java 11.

**Comment by kalexmills** [comment]
Looks like my workaround is to extend `ThrowableProblem` instead of `RuntimeException` -- but I got the idea from the docs that this was what `Exceptional` was built for. Perhaps it could be more clear that this won't work if your `BusinessException` already inherits from `RuntimeException`.

From the docs:
>If you already have an exception class that you want to extend, you should implement the "marker" interface Exceptional:
>
>public final class OutOfStockProblem extends BusinessException implements Exceptional

I'm going to mark this ticket as closed, because it seems that things may be working as expected.

**Comment by whiskeysierra** [comment]
With `Exceptional` we want to enforce that the whole chain of causes is also a proper problem. It's a bit awkward because `Throwable` itself is a class and since we can have only one super class, it's a bit ugly to come up with something that is compatible to Throwable but still allows to be implemented when needed without forcing too much on the cleint. 

> Looks like my workaround is to extend `ThrowableProblem` instead of `RuntimeException`

That is one option. Alternatively you can do the same trick as `ThrowableProblem` and enforce correct type in constructor and rely on it further down in the `getCaues`.
