### ISSUE TITLE
localizedMessage should not present if it is equal to message

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/problem#14]

**Comment by whiskeysierra** [comment]
Where shouldn't it be present? In JSON? It shouldn't be present at all.

**Comment by whiskeysierra** [comment]
Since we're not overriding `Throwable.getLocalizedMessage()` it will always use the default implementation which just delegates to `getMessage`, iirc. Since we don't support localization (yet?) we can just return null there.

**Comment by AlexanderYastrebov** [comment]
ProblemModule was not registered properly and that is why I observed unintended fields in output. Cosing this as unrelevant.
