### ISSUE TITLE
Extending AbstractThrowableProblem not working as expected in Kotlin

### ISSUE THREAD

**Issue by flansen** [zalando/problem#145]
When extending AbstractThrowableProblem in Java it works as expected.
Extending the class in Kotlin leads to a compile error: 

`Class 'MyProblem' is not abstract and does not implement abstract base class member public abstract fun getCause(): Exceptional! defined in org.zalando.problem.AbstractThrowableProblem`

## Description
Working Java Problem:
```
public class MyProblemJava extends AbstractThrowableProblem {

    public MyProblemJava(String message) {
        super(URI.create("https://www.google.de"), "My Problem", Status.BAD_REQUEST, message);
    }
}
```
The same problem converted to Kotlin
```
import org.zalando.problem.AbstractThrowableProblem
import org.zalando.problem.Status.BAD_REQUEST
import java.net.URI

class MyProblem(message: String?) : AbstractThrowableProblem(TYPE, "My Problem", BAD_REQUEST, message) {

    companion object {
        val TYPE = URI.create("https://www.google.de/workflow-problem")
    }
}
```
## Expected Behavior
MyProblem should not have to override getCause() as the Java class does not have to do, either.

## Actual Behavior
Compilation issue.

## Your Environment
* Version used: 0.22.0
* also found here: https://stackoverflow.com/questions/53761722/java-to-kotlin-conversion-extending-abstract-class

**Comment by whiskeysierra** [comment]
Sounds like a Kotlin issue, tbh. @lukasniemeier-zalando Have you seen something like this before?

**Comment by flansen** [comment]
What is really strange to me is that this works:
```
class MyProblem(message: String?) : AbstractThrowableProblem(TYPE, "My Problem", BAD_REQUEST, message) {

    companion object {
        val TYPE = URI.create("https://www.google.de/workflow-problem")
    }
    
    override fun getCause(): Exceptional? = super.cause
}
```

Looks like some interop-issue to me :/ any ideas?

**Comment by whiskeysierra** [comment]
I don't have enough kotlin know-how to help here. The workaround is good enough for me, tbh.

**Comment by leomelin** [comment]
I also bumped into this problem, so I think this should be reopened - something like this might work to fix this:
https://gist.github.com/leomelin/1dc5804a21be1cea92ab0d36d3f5081b#file-abstractthrowableproblem-java-L90

as AbstractThrowableProblem doesn't implement the `getCause` method. I have no idea if this is a Kotlin issue, if so then this should be reported to https://github.com/JetBrains/kotlin also

**Comment by whiskeysierra** [comment]
> as AbstractThrowableProblem doesn't override the `getCause` method

It inherits it from `ThrowableProblem`. There is no reason to implement it again:

https://github.com/zalando/problem/blob/21e28bcfbdb3984d0f26a2a44b729b88ddb5f709/problem/src/main/java/org/zalando/problem/ThrowableProblem.java#L38-L42

>  I have no idea if this is a Kotlin issue

Since it works in Java I'm inclined to say yes.

**Comment by lukasniemeier-zalando** [comment]
My best guess is that we are running into a variant of https://youtrack.jetbrains.com/issue/KT-6653, i.e. Kotlin-styled *properties* not properly overriding a Java getter. This may happen here as `Throwable` is a "mapped type" during compilation (see [here](https://kotlinlang.org/docs/reference/java-interop.html#mapped-types)), hence `ThrowableProblem#getCause()` is (erroneously) not overriding property `kotlin.Throwable#cause`.

**Comment by unlimitedsola** [comment]
This problem has gone worse with the new IR backend. There is no way to make the code compile with the new IR backend, even the workaround doesn't work anymore.
I've filed an issue at https://youtrack.jetbrains.com/issue/KT-45853

**Comment by jehrenzweig-leagueapps** [comment]
Looks like the issue that @unlimitedsola reported, wrt the IR backend ([https://youtrack.jetbrains.com/issue/KT-45853](https://youtrack.jetbrains.com/issue/KT-45853)), is fixed.  

This comment was posted with regards to the need to redundantly override `getCause()` with the same implementation as the superclass (i.e. `super.getCause()`):
```
Hi , you are right. This is caused by "Inconsistent override tree when Kotlin property accessor is 
covariantly overridden by a Java method" (https://youtrack.jetbrains.com/issue/KT-46042), 
which, unfortunately, we can't fix right away without deprecation cycle.
```
