### ISSUE TITLE
Ensure compatibility with RFC 7807 and update documentation

### ISSUE THREAD

**Issue by jhorstmann** [zalando/problem#16]
There seems to be an updated RFC regarding describing [Problem Details for HTTP APIs][1]. We should make sure to be compatible with this RFC and update the documentation accordingly.

 [1]: http://tools.ietf.org/html/rfc7807

**Comment by whiskeysierra** [comment]
By the looks of it, it's no longer a draft. Cool! After quickly skipping through it, I couldn't find any significant change. So it seems we're still compatible, aren't we?
