### ISSUE TITLE
Cannot extend Exception and implement Exceptional because getCause() signature is incompatible

### ISSUE THREAD

**Issue by gpaglia** [zalando/problem#167]
In the readme documentation you show how to extend an already existing Exception to create a Problem, by implementing the marker interface Exceptional:

> If you already have an exception class that you want to extend, you should implement the "marker" interface Exceptional:
> 

`public final class OutOfStockProblem extends BusinessException implements Exceptional
`
This does not work because Exceptional and Throwable both expose a getCause method with different, incompatible signatures.

How is that supposed to work?

Windows 10
Eclipse 4.13RC1
Java 11
Spring Boot 2.1.8.RELEASE
problem.spring.web 0.23.0

Thanks a lot,
GP

**Comment by whiskeysierra** [comment]
It works as long as you do two things: 

1. Override constructors that take a cause and declare the type as ThrowableProblem.
2. Override getCause and cast it (cast is safe since you control all entry points)

It's not ideal, but it works.

**Comment by gpaglia** [comment]
OK thanks, that worked.
G
