### ISSUE TITLE
Provide a github page for problem types

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem#17]
Right now we use the wiki, but a github page would yield a nicer URL:

    https://zalando.github.io/problem/constraint-violation

**Comment by LappleApple** [comment]
@whiskeysierra just finished editing the README in the Google Doc I shared with you. This would probably be a good idea. You can consolidate a lot here by replacing the entire section with a title +  list of links to specific files in this repo, titled by name of the problem type.

**Comment by whiskeysierra** [comment]
http://jekyllthemes.io/theme/22332559/harmony

**Comment by kakawait** [comment]
@whiskeysierra https://github.com/zalando/problem/wiki/constraint-violation does not work anymore.

**Comment by whiskeysierra** [comment]
@kakawait I accidentally disabled the wiki in all our projects, because I thought we don't use them anywhere. I was wrong :sweat_smile: :

**Comment by whiskeysierra** [comment]
See https://zalando.github.io/problem/
