### ISSUE TITLE
Add support for application/problem+xml

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/problem#19]

**Comment by whiskeysierra** [comment]
Not needed atm

**Comment by apescione** [comment]
Why doesn't your library support  application/problem+xml?
What shoud an API in Xml response whe an error occurs?
How can I extend or contribute your framework for that?
Thanks in advance.

**Comment by whiskeysierra** [comment]
> How can I extend or contribute your framework for that?

Sure. If you're willing to contribute a module, e.g. `problem-jaxb` or something like that which contains the necessary code to convert problems to XML, then I don't see a reason why this shouldn't be included.

> Why doesn't your library support application/problem+xml?

Zalando is not using XML, so there was no intrinsic need to support it.
