### ISSUE TITLE
Problem should override equals and hashcode 

### ISSUE THREAD

**Issue by aakavalevich** [zalando/problem#29]
I would like to write tests to compare thrown problems like this
`exception.expect(is(Problem.valueOf(MoreStatus.UNPROCESSABLE_ENTITY, "Some error")))`
org.hamcrest.core.Is compares objects using equals method of objects.
So to be able write those kind of tests I need Problem to override equals method.

**Comment by whiskeysierra** [comment]
Good catch, that totally slipped by me.

Under which circumstances would you consider two problems to be equals? Same values in the official properties (type, status, title, detail, instance)? Or including custom properties?

**Comment by whiskeysierra** [comment]
What about two different implementations? DefaultProblem vs. a custom implementation, e.g. OutOfStockProblem? I could use default problem to make it look 100% the same, but the java classes are still different. Implementing this symmetrical across an inheritance tree is going to be tricky.

**Comment by jhorstmann** [comment]
I don't like implementing `equals`/`hashCode` unless it's in a `final` class and there is an obvious implementation that everyone agrees about.

An alternative that I would prefer would be a separate artifact implementing specific hamcrest matchers for problems.

    exception.expect(ProblemMatchers.problemWithStatusAndMessage(MoreStatus.UNPROCESSABLE_ENTITY, "Some error"))

**Comment by whiskeysierra** [comment]
> Custom problems can override those methods themselves.

No, that would break the contract of *equals*:

1. It is reflexive: For any reference value x, x.equals(x) must return true.
2. **It is symmetric: For any reference values x and y, x.equals(y) must return true if and only if y.equals(x) return true.**
3. It is transitive. For any reference values x, y, and z, if x.equals(y) returns true and y.equals(z) returns true, then x.equals(z) must return true.
4. It is consistent. For any reference values x and y, multiple invocations of x.equals(y) consistently return true or consistently return false, provided no information used in equals comparisons on the object is modified.

> I don't like implementing equals/hashCode unless it's in a final class and there is an obvious implementation that everyone agrees about.

I agree. Doing this right is borderline impossible on interface level. I recommend reading *Chapter 3 of Effective Java Programming Language Guide By Joshua Bloch* on this.

**Comment by aakavalevich** [comment]
I would agree with this approach. That's fine for my case.

**Comment by whiskeysierra** [comment]
I'm hesitant to add this as a module here. Have you considered creating that module that @jhorstmann described yourself? I'd be happy to have a link to it in our readme.

**Comment by whiskeysierra** [comment]
`problem-hamcrest`?

**Comment by michaeltecourt** [comment]
@whiskeysierra Has this issue been abandoned ? How do you unit test without some sort of `equals` method or matcher ?
