### ISSUE TITLE
Provide support for flow id as extension to problem

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/problem#31]
Looks like problem definition allows extensions https://tools.ietf.org/html/draft-nottingham-http-problem-06#section-3

Flow id can be added as separate field to simplify debugging.
Integration with https://github.com/zalando/tracer may be considered.

**Comment by whiskeysierra** [comment]
Extensions yes (this is why we have Problem as an interface, the README shows some examples for this), but we already have any Trace ID already in the header, making it obsolete here. Clients should be sophisticated enough to read HTTP headers.
