### ISSUE TITLE
Implementation of Problem extending IOException

### ISSUE THREAD

**Issue by jhorstmann** [zalando/problem#32]
What do you think about adding another throwable problem implementation that is a checked instead of an unchecked exception? For convenience I would like to have this extend `IOException`. Reasons:

 - Problems are usually read from the network where you'd already have to deal with `IOExceptions`
 - Exceptions from jackson during json processing also extend `IOException`

**Comment by whiskeysierra** [comment]
We have the `Exceptional` marker interface that is meant to be used for mixing the Problem interface with other exception types. Maybe this would cover your use case already?

**Comment by whiskeysierra** [comment]
```java
public final class IOProblem extends IOException implements Exceptional {
    // TODO stuff
}
```

**Comment by whiskeysierra** [comment]
See #36
