### ISSUE TITLE
OffsetDateTime/LocalDateTime serialization not working 

### ISSUE THREAD

**Issue by SomeshK4** [zalando/problem#326]
OffsetDateTime and LocalDateTime serialization is not working and they are shown as array/complex object.  
## Description

While using spring boot 2.4 with zolando problem-spring-web and zolando problem-spring-web-starter, Java8 OffsetDateTime and LocalDateTime are not getting serialized properly and return as complex object/array like the example given below. When we remove the dependency the dates are getting serialized properly. When you override ObjectMapper configuration and register JavaTimeModule, Problem Module etc. , in that case also the dates are not getting serialized properly. For your information we are using jackson-datatype-jsr310 and jackson-datatype-jdk8. 
{
  "year": 2017,
  "month": "AUGUST",
  "era": "CE",
  "dayOfMonth": 1,
  "dayOfWeek": "TUESDAY",
  "dayOfYear": 213,
  "leapYear": false,
  "monthValue": 8,
  "chronology": {
      "id":"ISO",
      "calendarType":"iso8601"
   }
}

## Expected Behavior

OffsetDateTime and LocalDateTime should be serialized properly.

## Actual Behavior

OffsetDate and LocalDateTime are returned as complex object as shown above.

## Steps to Reproduce

1. Create a spring boot project having version 2.4 
2. Add jackson-datatype-jdk8 and jackson-datatype-jsr310 as dependency and other spring boot starter dependencies like starter security, starter web, starter oauth2 
3. Create Exception Handler that implements ProblemHandling, SecurityAdviceTrait and provide method inside the class @ExceptionHandler(Exception.class)
    ResponseEntity<Problem> handleOtherExceptions(
            final Exception exception,
            final NativeWebRequest request) {
        Problem problem = Problem
                .builder()
                .withTitle(Status.INTERNAL_SERVER_ERROR.getReasonPhrase())
                .withStatus(Status.INTERNAL_SERVER_ERROR)
                .withDetail(exception.getMessage())
                .withInstance(createProblemInstanceUUID())
                .build();
        log.error("Server Error : {}", problem.toString());
        return create(exception, problem, request);
    }
4. Run the application and try to throw an exception from some code then it will show everything including stacktrace, cause etc. 

## Context

Trying to use problem-spring-web and problem-spring-web-starter inside Spring boot 2.4 application having starter dependencies that are mentioned above. Intention is to provide method inside the Exception handler class so that custom problem exception will be returned or displayed on the postman.

ResponseEntity<Problem> handleValidationExceptions(final RuntimeException exception, NativeWebRequest request) {
        Problem problem = Problem.builder()
              
                .withTitle(Status.BAD_REQUEST.getReasonPhrase())
                .withStatus(Status.BAD_REQUEST)
                .withDetail(exception.getMessage())
         
                .build();

        log.warn("Validation error : {} ", problem.toString());
        return create(exception, problem, request);
    }

## Your Environment

* Version used: 0.27.0
* Link to your project:

**Comment by whiskeysierra** [comment]
> When you override ObjectMapper configuration and register JavaTimeModule, Problem Module etc. , in that case also the dates are not getting serialized properly.

That sounds very weird. Can you provide a failing test case?

**Comment by SomeshK4** [comment]
Here is the response I am getting 

"enrolmentDate": {
        "offset": {
            "totalSeconds": 3600,
            "id": "+01:00",
            "rules": {
                "transitions": [],
                "transitionRules": [],
                "fixedOffset": true
            }
        },
        "nano": 250000000,
        "year": 2017,
        "monthValue": 11,
        "dayOfMonth": 22,
        "hour": 14,
        "minute": 17,
        "second": 46,
        "month": "NOVEMBER",
        "dayOfWeek": "WEDNESDAY",
        "dayOfYear": 326
    }

Add for your information here is the pom.xml that I am using 

<properties>
        <java.version>11</java.version>
        <spring-boot-admin.version>2.4.0</spring-boot-admin.version>
        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
        <org.projectlombok.version>1.18.18</org.projectlombok.version>
        <log4j.version>2.14.1</log4j.version>
        <lmax.distruptor.version>3.4.2</lmax.distruptor.version>
        <vavr.version>0.10.3</vavr.version>
        <jib-maven-plugin.version>3.0.0</jib-maven-plugin.version>
        <zolando.problemdetails.version>0.27.0-RC.0</zolando.problemdetails.version>

        <docker.artifact.name>sst</docker.artifact.name>
        <docker.image.name>${docker.nexus.repository}/${docker.artifact.name}:${project.version}</docker.image.name>
        <docker.from.image>${docker.nexus.repository}/alpine-jdk8:${swish.docker.base.version}</docker.from.image>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ibm.db2</groupId>
            <artifactId>jcc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-jpamodelgen</artifactId>
            <version>6.0.0.Alpha7</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
            <version>${vavr.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>${spring-boot-admin.version}</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>3.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <version>0.18.0</version>
            <scope>test</scope>
        </dependency>

        
        
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-parameter-names</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>com.getswish</groupId>
            <artifactId>annotations</artifactId>
            <version>1.0.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.getswish</groupId>
            <artifactId>data-types</artifactId>
            <version>1.0.0.5</version>
        </dependency>

        <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>problem-spring-web-starter</artifactId>
            <version>${zolando.problemdetails.version}</version>
        </dependency>

    </dependencies>


Here is the configuration files but these configuration files are only used when I use problem-spring-web not the starter module

@Configuration
public class ObjectMapperConfiguration {

    @Bean
    @Primary
    public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder) {
        ObjectMapper objectMapper = builder.createXmlMapper(false).build();
        objectMapper.registerModule(new ProblemModule().withStackTraces(false))
                .registerModule(new ConstraintViolationProblemModule());
        return objectMapper;
    }
}

@Configuration
public class ProblemConfiguration {

    @Bean
    ConstraintViolationProblemModule constraintViolationProblemModule() {
        return new ConstraintViolationProblemModule();
    }

    @Bean
    ProblemModule problemModule() {
        return new ProblemModule().withStackTraces(false);
    }
}

**Comment by whiskeysierra** [comment]
Are you sure the JavaTimeModule is registered with the object mapper?

**Comment by SomeshK4** [comment]
According to the spring boot reference docs, if you have added jackson-datatype-jsr310 dependency then the provider will be automatically registered i.e JavaTimeModule. But just to make sure that I tried to explicity register JavaTimeModule but then didn't work even. It is bit weird behavior but this is how it is. I shared all the information that is required but if you need anything else please let me know.

**Comment by whiskeysierra** [comment]
*problem* doesn't do anything special with Jackson. If certain data types are not de/serialized correctly, it's definitely related to the setup of the underlying `ObjectMapper`.

I'd suggest you run your code with a debugger to double-check which modules are actually installed/registered on the `ObjectMapper`.
Other than that, this is not an issue that is related to the problem library.
