### ISSUE TITLE
wrong name in problem/module-info.java

### ISSUE THREAD

**Issue by emweber** [zalando/problem#329]
org.zalando.problem**.gson**

**Comment by monterinio** [comment]
any update on this?

**Comment by whiskeysierra** [comment]
We're not using the module system, hence it's hard to test this. But we're happy to accept contributions.

**Comment by emweber** [comment]
We are hit by the wrong name when we try to convert the jar into an OSGI-bundle (using the p2-maven-plugin).

**Comment by tinolazreg** [comment]
Any possibility to get @emweber bug-fix merged in soon?
