### ISSUE TITLE
api-guardian "soft dependency"

### ISSUE THREAD

**Issue by floriankoch0360** [zalando/problem#341]
When using the library without depending on `org.apiguardian:apiguardian-api`, on compilation several warnings will occur:

    unknown enum constant Status.STABLE
    unknown enum constant Status.MAINTAINED

## Description 
The api-guardian (introduced in #58) isn't listed as mandatory dependency for the library. Actually, it isn't even mentioned in the README. So, when using the lib as documented one will encounter said warnings on compilation.

## Expected Behavior
Either make the dependency mandatory, or at least mention it in the README.

## Actual Behavior
Warnings will occur on compilation.

## Your Environment

* Version used: 0.26.0

**Comment by whiskeysierra** [comment]
Can you share a sample project where I can see those warnings?

I haven't seen those before.

**Comment by floriankoch0360** [comment]
I can try to create a minmal example, since I can't share the code I'm working on

**Comment by floriankoch0360** [comment]
i managed to get it working fairly simply, please have a look here:
https://github.com/floriankoch0360/zalando-problem-demo

you can uncomment the line 21 in build.gradle to fix the warning

**Comment by whiskeysierra** [comment]
Looks like JUnit themselves switched to compile dependencies to get around those warnings: https://stackoverflow.com/questions/46702273/warning-unknown-enum-constant-status-stable

**Comment by whiskeysierra** [comment]
@floriankoch0360 Care to create a PR to remove the specific scope for that dependency (implicitly making it *compile*)?

**Comment by floriankoch0360** [comment]
I created the PR, currently totally untested: https://github.com/zalando/problem/pull/342
I had the hope CI would handle testing for me, however workflow execution must be approved first
