### ISSUE TITLE
Add a link to RFC 7807 in README

### ISSUE THREAD

**Issue by cowtowncoder** [zalando/problem#410]
Since this module adds support for JSON "problem" structure, as per RFC 7807:

https://www.rfc-editor.org/rfc/rfc7807

it would make sense to add a link on README to make it easier to find, by anyone looking for support. I can provide a PR if need be.

Also: I could be wrong but I am guessing this might also work with Jackson XML module (for the other type specified by RFC 7807, for XML); or if not, might be easy to modify to do so (if naming convention varies, for example).

**Comment by whiskeysierra** [comment]
![image](https://user-images.githubusercontent.com/429981/235936020-c1585056-debb-4195-8b71-2b10baf619c7.png)
