### ISSUE TITLE
Remove JaxRS dependency

### ISSUE THREAD

**Issue by cbornet** [zalando/problem#51]
The dependency on JAX-RS 2 is hard because you can't use the lib with another one that depends on JAX-RS 1.
Especially you can't use it with spring-cloud-netflix as Ribbon and Eureka both use jersey1 (see https://github.com/spring-cloud/spring-cloud-netflix/issues/846)

It seems to me that only the Status/StatusType classes are used from JAX-RS. This doesn't represent a lot of code so it would be easy to duplicate. Also, it's always nice to remove a dependency and will make the lib smaller.

Of course I can PR if you want (and I would also do the PR for problem-spring-web).

Context : I want to bring Problem errors to [JHipster](http://www.jhipster.tech/) which uses Spring-Cloud/Netflix/Eureka/Ribbon

**Comment by whiskeysierra** [comment]
> It seems to me that only the Status/StatusType classes are used from JAX-RS.

Correct.

> This doesn't represent a lot of code so it would be easy to duplicate. Also, it's always nice to remove a dependency and will make the lib smaller.

Yes, but that would be a breaking change. That would at least require that we also do this change in [zalando/problem-spring-web](https://github.com/zalando/problem-spring-web).

**Comment by whiskeysierra** [comment]
In general I'd be fine with switching from `StatusType` to int.

**Comment by cbornet** [comment]
@whiskeysierra yes, you're right. Switching to int (Integer ?) would probably be the best since only the code is serialized.
Do I PR ?

**Comment by whiskeysierra** [comment]
> Do I PR ?

It would be highly appreciated!

**Comment by cbornet** [comment]
Do you prefer Integer or enum ?

**Comment by whiskeysierra** [comment]
I think `Integer` without any static constants should be enough. I don't want to maintain a complete list and enum would be too restricting since it needs to be extensible as dictated by the RFC.

**Comment by cbornet** [comment]
The reasonPhrase is used in [GenericProblems](https://github.com/zalando/problem/blob/80e71ea52faa2ba620894c901003591317b310a0/problem/src/main/java/org/zalando/problem/GenericProblems.java#L13) to set the Problem title.
What should I do about it ?

Abou enum extensibility, we can use an interface like `StatusType`. So users can add there own status enum by implementing it.

**Comment by whiskeysierra** [comment]
> The reasonPhrase is used in GenericProblems to set the Problem title.
> What should I do about it ?

Good question. Maintaining a list of status code + reason phrases is equivalent to maintaining a complete status enum itself. Something that I'd like to avoid.

> Abou enum extensibility, we can use an interface like StatusType. So users can add there own status enum by implementing it.

Yes, that's true. In fact I used JAX-RS for this very reason. And because it contained an enum already that I didn't have to maintain myself.

I'm torn between the following two options:
1. a simple int (or Integer), no reason phrase, no enum/dictionary of statuses that we need to maintain
2. an interface + an enum of defaults, that introduces a new place where status codes are defined (in addition to JAX-RS, Spring, ...). But you get typed status objects + reason phrases.

I see good arguments for both. Which one do you prefer?

**Comment by cbornet** [comment]
I think 2/ is nicer for the end-user since he gets the status code meaning instantly.
As for maintaining the enum, I think it's not a big deal since we can provide the most commonly used statuses and people who use exotic ones can easily add them in their own code (just like what is done in JAX-RS). They will even enjoy the java8 default methods of the interface (which is not the case with JAX-RS).
I'll do the PR based on 2/ then we can discuss on it if you're OK.

**Comment by whiskeysierra** [comment]
> I'll do the PR based on 2/ then we can discuss on it if you're OK.

Sounds good!
