### ISSUE TITLE
Does not work with Jackson 2.9.x

### ISSUE THREAD

**Issue by piotrowskirafal** [zalando/problem#53]
Zalando/problem does not work correctly with Jackson version `2.9.x` - stacktrace is missing. Please see the test `ProblemMixInTest.shouldSerializeStacktrace`. I've created a fork with jackson `2.9.3`: https://github.com/piotrowskirafal/problem
It seems that the last compatible Jackson version where everything works fine is `2.8.11`.

**Comment by whiskeysierra** [comment]
@piotrowskirafal Thanks for reporting this! :tada: I created #54 to include a fix.

**Comment by whiskeysierra** [comment]
@piotrowskirafal I released the fix as 0.20.1 to central.

**Comment by piotrowskirafal** [comment]
@whiskeysierra Cool 👍 , thanks for the fix!

**Comment by kschulst** [comment]
@whiskeysierra will there be a release of [problem-spring-web](https://github.com/zalando/problem-spring-web) as well?

**Comment by whiskeysierra** [comment]
@kschulst I'll prepare one, but you don't need to wait for it. As long as you specify the correct versions, everything should already work.

**Comment by kschulst** [comment]
yep, I'm doing that now ... Was just thinking about users that pull in zalando-problem implicitly via the problem-spring-web lib that might not be aware of this fix.

**Comment by whiskeysierra** [comment]
@kschulst I release problem-spring-web [0.22.1](https://github.com/zalando/problem-spring-web/releases/tag/0.22.1) to central.
