### ISSUE TITLE
Stack traces and causal chains in the Readme.md file might be inaccurate

### ISSUE THREAD

**Issue by CrackPT** [zalando/problem#83]
## Description
[Stack traces and causal chains](../#stack-traces-and-causal-chains)

## Expected Behavior

> ```java
> ThrowableProblem problem = Problem.builder()
>     .withType(URI.create("https://example.org/order-failed"))
>     .withTitle("Order failed")
>     .withStatus(BAD_REQUEST)
>     .withCause(Problem.builder()
>       .withType(URI.create("https://example.org/out-of-stock"))
>       .withTitle("Out of Stock")
>       .withStatus(BAD_REQUEST)
>       .build())
>     .build();
>     
> problem.getCause(); // standard API of java.lang.Throwable
> ```
> 
> Will produce this:
> 
> ```json
> {
>   "type": "https://example.org/order-failed",
>   "title": "Order failed",
>   "status": 400,
>   "cause": {
>     "type": "https://example.org/out-of-stock",
>     "title": "Out of Stock",
>     "status": 400,
>     "detail": "Item B00027Y5QG is no longer available"
>   }
> }
> ```

## Actual Behavior
> ```java
> ThrowableProblem problem = Problem.builder()
>     .withType(URI.create("https://example.org/order-failed"))
>     .withTitle("Order failed")
>     .withStatus(BAD_REQUEST)
>     .withCause(Problem.builder()
>       .withType(URI.create("about:blank"))
>       .withTitle("Out of Stock")
>       .withStatus(BAD_REQUEST)
>       .build())
>     .build();
>     
> problem.getCause(); // standard API of java.lang.Throwable
> ```
> 
> Will produce this:
> 
> ```json
> {
>   "type": "https://example.org/order-failed",
>   "title": "Order failed",
>   "status": 400,
>   "cause": {
>     "type": "https://example.org/out-of-stock",
>     "title": "Out of Stock",
>     "status": 400,
>     "detail": "Item B00027Y5QG is no longer available"
>   }
> }
> ```

## Possible Fix
Replace **about:blank** with **https://example.org/out-of-stock**

## Context
Inaccurate documentation

**Comment by whiskeysierra** [comment]
Thanks a lot! I fixed it.
