### ISSUE TITLE
Remove Google GAG dependency

### ISSUE THREAD

**Issue by bertramn** [zalando/problem#89]
Would it be possible to remove the Google gag library?

This library has no practical function (being an April's fool joke) and it pollutes the dependency tree for enterprise deployments. Ideally a library like this should be dependency free or at least none for current Java version and optional ones for older JDKs.

https://github.com/zalando/problem/blob/0.20.3/problem/pom.xml#L35-L39

We think the problem library is a really good idea and reducing it's dependencies would make it even more awesome.

**Comment by whiskeysierra** [comment]
I'll change the scope to provided.

**Comment by whiskeysierra** [comment]
@bertramn Fixed as of 0.21.0. Thanks for raising the issue :tada:

**Comment by bertramn** [comment]
Hmm, marking the dependencies as provided will not remove them from being required at runtime on the classpath. What I was hoping for was to remove the dependency all together. I don’t have access to an IDE right now but the test would be to remove the gag dependency and recompile. Similar the findbugs (nullable) api should be replaced with something more recent/part of java 8. Will have a closer look towards the weekend.

**Comment by whiskeysierra** [comment]
> will not remove them from being required at runtime on the classpath

That is true for typical java classes, but annotations are not needed at runtime.

**Comment by whiskeysierra** [comment]
> (nullable) api should be replaced with something more recent/part of java 8

There is nothing that is more official than the findbugs annotations, afaik.

**Comment by bertramn** [comment]
No worries, did up a quick test and looks like Findbugs, GAG and Apiguardian can be marked `provided`.

https://gist.github.com/bertramn/e3cf2e55077664112141827e45b919e7
